version: "2"
services:
    frontend:
        image: webapp-client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - api
        networks:
            webappnetwork
    backend:
        image: webapp-api
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
        networks:
            webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
        - ./data-node:/data/db
        ports:
        - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
        - webappnetwork
networks:
    webappnetwork:
        driver: bridge